apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - repository.yml
  - release.yml
  # - ingress.yml
configMapGenerator:
  - name: argocd-values
    files:
      - values.yml=values.yml
configurations:
  - kustomizeconfig.yml
